- name: latest | Get the latest version from GitHub repository
  ansible.builtin.uri:
    url: "https://api.github.com/repos/consensys/teku/releases/latest"
    method: GET
    status_code: 200
    return_content: true
  register: _latest_release_response

- name: latest | Set the version variable
  ansible.builtin.set_fact:
    _teku_version: "{{ _latest_release_response.json.tag_name }}"

- name: latest | Validate the discovered Teku version
  ansible.builtin.assert:
    that: _teku_version is search("^[0-9]+\.[0-9]+\.[0-9]+$")
    fail_msg: "Discovered version [{{ _teku_version }}] is not valid"

- name: latest | Information
  ansible.builtin.debug:
    msg: "Latest Teku version is {{ _teku_version }}"

