---
- name: Ensure we have sane configuration
  block:
    - name: Check teku version supplied
      ansible.builtin.fail:
        msg: You must set "teku_version" for this role to run
      when: teku_version is not defined

# Retrive latest version when teku_version == 'latest'
- name: Include task to retrieve latest version
  ansible.builtin.include_tasks: latest.yml
  when: teku_version == 'latest'

- name: Include OS and distribution specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true

- name: Get IP address to bind to if not provided
  ansible.builtin.include_tasks: network.yml
  when: not teku_host_ip

- name: Install teku
  ansible.builtin.include_tasks: install.yml

- name: Teku monolith
  ansible.builtin.include_tasks: monolith.yml
  when: teku_monolith_enabled 

- name: Teku beacon
  ansible.builtin.include_tasks: beacon.yml
  when: > 
    not teku_monolith_enabled|bool and
    teku_beacon_enabled|bool

- name: Teku validator
  ansible.builtin.include_tasks: validator.yml
  when: > 
    not teku_monolith_enabled|bool and
    teku_validator_enabed|bool

# - name: Set version info on a local file
#   include_tasks: "tags.yml"