---
- name: main | Ensure we have sane configuration
  block:
    - name: Check teku version supplied
      ansible.builtin.fail:
        msg: You must set "teku_version" for this role to run
      when: teku_version is not defined

# Retrive latest version when teku_version == 'latest'
- name: main | Include task to retrieve latest version
  ansible.builtin.include_tasks: latest.yml
  when: teku_version == 'latest'

- name:  main | Include OS and distribution specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true

- name: main | Get IP address to bind to if not provided
  ansible.builtin.include_tasks: network.yml
  when: not teku_host_ip

- name: main | Install teku
  ansible.builtin.include_tasks: install.yml

- name: main | Teku combined
  ansible.builtin.include_tasks: combined.yml
  when: teku_combined_enabled 

- name: main | Teku beacon
  ansible.builtin.include_tasks: beacon.yml
  when: > 
    not teku_combined_enabled|bool and
    teku_beacon_enabled|bool

- name: main | Teku validator
  ansible.builtin.include_tasks: validator.yml
  when: > 
    not teku_combined_enabled|bool and
    teku_validator_enabled|bool

# - name: Set version info on a local file
#   include_tasks: "tags.yml"