---
- name: Ensure we have sane configuration
  block:
    - name: Check teku version supplied
      ansible.builtin.fail:
        msg: You must set "teku_version" for this role to run
      when: teku_version is not defined

# Retrive latest version when teku_version == 'latest'
- name: Include task to retrieve latest version
  ansible.builtin.include_tasks: "latest.yml"
  when: teku_version == 'latest'

- name: Include OS and distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true

- name: Install teku
  include_tasks: "install.yml"

- name: Run OS specific installation tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}/install.yml"
        - "{{ ansible_os_family|lower }}/install.yml"
      skip: true

- name: Get IP address to bind to if not provided
  include_tasks: "network.yml"
  when: not teku_host_ip

- name: Create config
  include_tasks: "config.yml"

- name: Create teku service
  include_tasks: "service.yml"
