---
name: echo

on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'

jobs:
  lint:
    name: echo
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      
